---
# GoReleaser docs: https://goreleaser.com/intro/
# This is used to build the mtcli binary upon pushing a tag.
# When CGO_ENABLED=1 we can't cross compile, only targeting Linux.
# Tag needs to respect Semver: https://semver.org/
# Validate config with: $ goreleaser check
project_name: mtcli
before:
  hooks:
    - make check
builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
      - CC=gcc
      # required by opm to extract sql-based catalog
      - CGO_CFLAGS=-DSQLITE_ENABLE_JSON1
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/mtcli
    ldflags:
      - -s -w
      - -X 'github.com/mt-sre/addon-metadata-operator/internal/cmd.version={{.Version}}'
      - -X 'github.com/mt-sre/addon-metadata-operator/internal/cmd.commit={{.Commit}}'
      - -X 'github.com/mt-sre/addon-metadata-operator/internal/cmd.date={{.Date}}'
      - -X 'github.com/mt-sre/addon-metadata-operator/internal/cmd.builtBy=goreleaser'
  - id: darwin-amd64
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
      - CC=o64-clang
      # required by opm to extract sql-based catalog
      - CGO_CFLAGS=-DSQLITE_ENABLE_JSON1
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/mtcli
    ldflags:
      - -s -w
      - -X 'github.com/mt-sre/addon-metadata-operator/internal/cmd.version={{.Version}}'
      - -X 'github.com/mt-sre/addon-metadata-operator/internal/cmd.commit={{.Commit}}'
      - -X 'github.com/mt-sre/addon-metadata-operator/internal/cmd.date={{.Date}}'
      - -X 'github.com/mt-sre/addon-metadata-operator/internal/cmd.builtBy=goreleaser'
          
archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
