---
on:
  push:
    branches:
      - yashvardhan/support-ci-to-push-images

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into registry.redhat.io
      uses: docker/login-action@master
      with:
        registry: registry.redhat.io
        username: ${{secrets.REDHAT_REGISTRY_USERNAME}}
        password: ${{secrets.REDHAT_REGISTRY_PASSWORD}}

    - name: check stuff
      run: |-
        echo ${{github.sha}}

    - name: Build image
      run: |-
        docker build -t quay.io/ykukreja/test-mtcli-empty:latest -f Dockerfile.build .
        docker tag quay.io/ykukreja/test-mtcli-empty:latest quay.io/ykukreja/test-mtcli-empty:${{github.sha}}

    - name: Log into quay.io
      uses: docker/login-action@master
      with:
        registry: quay.io
        username: ${{secrets.QUAY_REGISTRY_USERNAME}}
        password: ${{secrets.QUAY_REGISTRY_PASSWORD}}

    - name: Push into quay.io
      run:  |-
        docker push quay.io/ykukreja/test-mtcli-empty:latest
        docker push quay.io/ykukreja/test-mtcli-empty:${{github.sha}}
